# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gate_status', models.PositiveSmallIntegerField(choices=[(1, 'HIGH'), (0, 'LOW')])),
            ],
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gateactivity',
            name='responsible_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_activity_guest', to='api.Guests'),
        ),
        migrations.AddField(
            model_name='gateactivity',
            name='responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_activity_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
