# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateactivity',
            name='responsible_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_activity_guest', to='api.Guests'),
        ),
        migrations.AlterField(
            model_name='gateactivity',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_activity_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
