# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20170731_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('granted_on', models.DateField(auto_now_add=True)),
                ('starts_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_on', models.DateTimeField()),
                ('once_off', models.BooleanField(default=False)),
                ('once_off_used', models.BooleanField(default=False)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_by_user', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_for_guest', to='api.Guests')),
            ],
        ),
    ]
