# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_guestpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateactivity',
            name='responsible_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_interactions', to='api.Guests'),
        ),
        migrations.AlterField(
            model_name='gateactivity',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestpermissions',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guestpermissions',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.Guests'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
